name = "zegu-nav"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_OWNER = "zeguchuanmei"
GITHUB_BRANCH = "main"
GITHUB_REPO = "zegu_navsphere_data"

GITHUB_ID = "Ov23liFaqpnIopVZ0ZbG"
NEXTAUTH_URL = "https://nav.xque.net/api/auth"
NEXT_PUBLIC_API_URL="https://nav.xque.net"

